codecov:
  notify:
    require_ci_to_pass: yes
    after_n_builds: 1
    wait_for_ci: no
  branch: master

coverage:
  status:
    patch:
      default: off
      pr_coverage:
        target: 75%
    project:
      default: off
      minimum:
        target: 75%
      decrement:
        target: auto
        threshold: 0.5%
        if_not_found: success
comment:
  layout: "diff, flags"
  behavior: default
  require_changes: false
  require_base: no
  require_head: no
  branches: null